# The example configuration fits https://github.com/aws-robotics/aws-robomaker-hospital-world
model_name_patterns: [
  "actor",
]
link_name_patterns: [
  "Scrubs",
  "PatientWheelChair",
  "MaleVisitorSit",
  "VisitorKidSit",
  "FemaleVisitorSit"
]
